### ISSUE TITLE
geom_label makes the plot function slow 

### ISSUE THREAD

**Issue by dvaiman** [holgstr/fme#12]
Thanx for a great package. The geom_label in the univariate plot makes the plot() function slow (maybe in the other functions also) when using larger datasets as it plots a label (AME) for each data point. Maybe use annotate.

Also is it possible to get info how to modify the ggplot object (plot()) other than bins and how to get the data frame that it uses.

And if I may ask, is it possible to take the mean of the FME in different groups. Is this then called AME?
    
Thanks again for a much needed package.

**Comment by holgstr** [comment]
Thanks for the feedback Daniel! We are always happy to improve the package and fix bugs.

> The geom_label in the univariate plot makes the plot() function slow (maybe in the other functions also) when using larger datasets as it plots a label (AME) for each data point
1. Could you provide a short reproducible code example for this? For a univariate plot, we use `geom_label`, which should produce _just one_ label in the plot to give the AME estimate.
> Also is it possible to get info how to modify the ggplot object (plot()) other than bins and how to get the data frame that it uses.
2. You can extract the results of an `"ForwardMarginalEffect"` object that has been created with `effects <- fme(...)` via calling `effects$results`, which gives a `data.table` of the sample ids and computed effects. You can find an [example in the vignette](https://holgstr.github.io/fmeffects/articles/fmeffects.html#univariate-effects). While we use hexagon bins, you can always construct your own plots using the raw data from `results`.
> And if I may ask, is it possible to take the mean of the FME in different groups. Is this then called AME?
3. Yes, you can compute the mean of the FMEs in a group, which is called conditional AME (cAME), i.e. the average FME conditional on the observation coming from a pre-defined subspace of the data. The package has a function to detect such subgroups where average effects are markedly different ([see here](https://holgstr.github.io/fmeffects/articles/fmeffects.html#regional-interpretations)), but of course you can define subgroups based on your own criteria and then interpret the within-group mean FME as cAME.

**Comment by dvaiman** [comment]
Thanx! 

1. I have an reproducible example (maybe not that minimal) below that should work, I borrowed some of the code you had on github. I did not understand why the plot took so much time for me to render so I had to see the function to see what calculations were performed.

2. Thanx

3. Thanx, reason I was asking is that Im using it for getting the cAME with, for instance, different occupational groups in different time windows.

4. I have another question that is more about if it is possible to do with the results. Say I have a step size of 90 days (on a x-axis that is 5 years) and I want to calculate the cumulative cAME for each 90 days on the x axis and plot it on the same plot as an function over time. would this be a reasonable tought/calculation? My tought is that it would give the effect of the whole X-axis/time period. This would be in the univariate plot with AME and  `geom smooth`. 

```r
library(ggplot2)
library(dplyr)
library(tibble)

# Data
set.seed(123)
obs_id <- 1:30000
fme_values <- rnorm(30000, mean = 0.1, sd = 0.05)
fme_values <- ifelse(fme_values < 0, 0.01, fme_values)
results <- tibble(
  obs.id = obs_id,
  fme = fme_values
)
Time_change <- runif(30000, min = 0, max = 2000)
data.step <- tibble(
  Time_change = Time_change
)
combined_df <- bind_cols(results, data.step)
combined_df <- combined_df %>% rename(x1 = Time_change)

# Calculate statistics
range_x1 <- diff(range(combined_df$x1, na.rm = TRUE))
min_x1 <- min(combined_df$x1, na.rm = TRUE)
max_x1 <- max(combined_df$x1, na.rm = TRUE)

range_fme <- diff(range(combined_df$fme, na.rm = TRUE))
min_fme <- min(combined_df$fme, na.rm = TRUE)

mean_fme <- mean(combined_df$fme, na.rm = TRUE)

### Create Plot Version 1: Using geom_label ###

plot_geom_label <- ggplot(combined_df, aes(x = x1, y = fme)) +
  stat_summary_hex(aes(z = fme), fun = length, bins = 40) +
  xlim(NA, max_x1 + 0.15 * range_x1) +
  ylim(min_fme - 0.1 * range_fme, NA) +
  scale_fill_gradient(
    name = "Count",
    low = "gray87", high = "black",
    breaks = function(x) { unique(round(pretty(x, n = 3))) }
  ) +
  geom_rug(sides = "b", length = unit(0.015, "npc")) +
  geom_smooth(
    aes(x = x1, y = fme), 
    se = FALSE, 
    linetype = "dashed", 
    linewidth = 0.7, 
    color = "black"
  ) +
  annotate(
    "segment",
    x = 0.5 * (min(combined_df$x1) + max(combined_df$x1)) - 45,  
    xend = 0.5 * (min(combined_df$x1) + max(combined_df$x1)) + 45,
    y = min_fme - 0.06 * range_fme,
    yend = min_fme - 0.06 * range_fme,
    colour = 'black', 
    size = 1,
    arrow = arrow(length = unit(0.2, "cm")),
    lineend = "round", 
    linejoin = "mitre"
  ) +
  geom_hline(lwd = 1.2, yintercept = mean_fme) +
  geom_label(
    x = max_x1 + 0.1 * range_x1, 
    y = mean_fme, 
    label = "AME", 
    size = 3, 
    fill = 'white'
  ) +
  labs(
    x = "Time_change",
    y = "FME"
  ) +
  theme_bw() +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 0.7),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(colour = "black", size = 10),
    axis.text.y = element_text(colour = "black", size = 10),
    legend.title = element_text(color = "black", size = 12),
    legend.text = element_text(color = "black", size = 10)
  )

### Create Plot Version 2: Using annotate for the Label ###

plot_annotate <- ggplot(combined_df, aes(x = x1, y = fme)) +
  stat_summary_hex(aes(z = fme), fun = length, bins = 40) +
  xlim(NA, max_x1 + 0.15 * range_x1) +
  ylim(min_fme - 0.1 * range_fme, NA) +
  scale_fill_gradient(
    name = "Count",
    low = "gray87", high = "black",
    breaks = function(x) { unique(round(pretty(x, n = 3))) }
  ) +
  geom_rug(sides = "b", length = unit(0.015, "npc")) +
  geom_smooth(
    aes(x = x1, y = fme), 
    se = FALSE, 
    linetype = "dashed", 
    linewidth = 0.7, 
    color = "black"
  ) +
  annotate(
    "segment",
    x = 0.5 * (min(combined_df$x1) + max(combined_df$x1)) - 45, 
    xend = 0.5 * (min(combined_df$x1) + max(combined_df$x1)) + 45,
    y = min_fme - 0.06 * range_fme,
    yend = min_fme - 0.06 * range_fme,
    colour = 'black', 
    size = 1,
    arrow = arrow(length = unit(0.2, "cm")),
    lineend = "round", 
    linejoin = "mitre"
  ) +
  geom_hline(lwd = 1.2, yintercept = mean_fme) +
  annotate(
    "label",
    x = max_x1 + 0.1 * range_x1, 
    y = mean_fme, 
    label = "AME", 
    size = 3, 
    fill = 'white'
  ) +
  labs(
    x = "Time_change",
    y = "FME"
  ) +
  theme_bw() +
  theme(
    panel.border = element_rect(colour = "black", fill = NA, size = 0.7),
    axis.title = element_text(size = 12),
    axis.text.x = element_text(colour = "black", size = 10),
    axis.text.y = element_text(colour = "black", size = 10),
    legend.title = element_text(color = "black", size = 12),
    legend.text = element_text(color = "black", size = 10)
  )

### Display the Plots ###

# Plot using geom_label
tictoc::tic()
print(plot_geom_label)
tictoc::toc()

# Plot using annotate
tictoc::tic()
print(plot_annotate)
tictoc::toc()
```

**Comment by holgstr** [comment]
Thanks for the example @dvaiman! I see the performance issue regarding `geom_label`, will fix this promptly! As to the cAME:

> 3. Thanx, reason I was asking is that Im using it for getting the cAME with, for instance, different occupational groups in different time windows.

This depends on the structure of the variables. The cAME is **not** the smoothed dashed line that runs through the univariate `FME` plot. The smooth line is just a visualization tool for detecting potential heterogeneity in FMEs. The cAME is a simple average effect for individuals within a subgroup, so its calculated always as a simple mean. I don't know if this is what you meant, so this is just to clarify.

> 4. I have another question that is more about if it is possible to do with the results. Say I have a step size of 90 days (on a x-axis that is 5 years) and I want to calculate the cumulative cAME for each 90 days on the x axis and plot it on the same plot as an function over time. would this be a reasonable tought/calculation? My tought is that it would give the effect of the whole X-axis/time period. This would be in the univariate plot with AME and geom smooth.

See my answer above. I think what you desire is something one could call a smooth, time-dependent FME that is then accumulated over time. This implies first estimating the FME as a smooth function that depends on the value of time, and then accumulating the values of this smooth function over a number of discrete time steps. Is this what you had in mind? In this case, this is not interpretable as an AME or cAME. I will leave [this reference](https://link.springer.com/article/10.1007/s10618-023-00993-x) here for you in case you have more questions.

**Comment by holgstr** [comment]
@dvaiman The fix is now on GitHub, you can use <devtools> to install the GitHub version. Thanks!
