### ISSUE TITLE
Discrepancy in calculation beween `fmeffects::ame()` and `marginaleffects::avg_slopes()`.

### ISSUE THREAD

**Issue by Hirototensho** [holgstr/fme#4]
Dear holgstr, scholbeck and teunbrand

I hope this message finds you well. My name is Hiroto Tensho, and I would like to express my appreciation for your excellent work in developing the `meffects` package. I have also had the opportunity to review your research papers, which were enlightening.

I have been utilizing the functionalities of `fmeffects` within the empirical analysis in econometrics. During my recent exploration, I encountered a disparity in the results obtained from `fmeffects::ame()` when compared to the output of `marginaleffects::avg_slopes()` for logistic regression. While the output of two functions are similar in magnitude there is an inversion in the sign of the results between the `ame()` and `avg_slopes()`.

For instance, when using:

``` r
pacman::p_load(tidyverse, tidymodels, fmeffects)

data("Mroz87", package = "sampleSelection")

# the target variable 'lfp’ is 0, 1 dummy variable.
# now convert 'lfp’ and ’city’ to factor for using in parsnip.
Mroz87 <- Mroz87 |>
  mutate(lfp = factor(lfp), city = factor(city))

levels(Mroz87$lfp)
#> [1] "0" "1"
```

``` r
logistic_parsnip <-
  logistic_reg(engine = "glm") |>
  fit(
    lfp ~ nwifeinc + educ + exper + I(exper^2) + age + kids5 + kids618,
    data = Mroz87
    )

coef(logistic_parsnip$fit) |> round(4)
#> (Intercept)    nwifeinc        educ       exper  I(exper^2)         age 
#>      0.4255     -0.0213      0.2212      0.2059     -0.0032     -0.0880 
#>       kids5     kids618 
#>     -1.4434      0.0601
```

``` r
overview <- ame(
  model = logistic_parsnip,
  data = Mroz87,
  target = "lfp"
  )

overview$results |>
  filter(AME != "0") |> 
  arrange(Feature)
#>    Feature step.size     AME     SD    0.25    0.75   n
#> 1      age         1  0.0158 0.0054   0.012  0.0206 753
#> 2     educ         1  -0.039 0.0139 -0.0516 -0.0285 753
#> 3    exper         1 -0.0249 0.0134 -0.0355 -0.0131 753
#> 4    kids5         1  0.2576 0.0845  0.2012  0.3308 753
#> 5  kids618         1 -0.0107 0.0037 -0.0141 -0.0079 753
#> 6 nwifeinc         1  0.0038 0.0013  0.0028   0.005 753

marginaleffects::avg_slopes(logistic_parsnip$fit)
#> 
#>      Term Estimate Std. Error      z Pr(>|z|)    S    2.5 %    97.5 %
#>  age      -0.01572    0.00238 -6.603   <0.001 34.5 -0.02039 -0.011053
#>  educ      0.03950    0.00729  5.414   <0.001 24.0  0.02520  0.053794
#>  exper     0.02543    0.00224 11.369   <0.001 97.1  0.02104  0.029809
#>  kids5    -0.25775    0.03194 -8.069   <0.001 50.3 -0.32036 -0.195149
#>  kids618   0.01073    0.01333  0.805   0.4208  1.2 -0.01540  0.036868
#>  nwifeinc -0.00381    0.00148 -2.571   0.0101  6.6 -0.00672 -0.000906
#> 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
#> Type:  response
```

for example.  AME for 'age' from `fmeffects::ame()` is 0.0158, however from `marginaleffects::avg_slopes()` it is -0.01572, so absolute values is similar, however sign is different. 

It seems that `fmeffects::fme()` and `fmeffects::ame()` are calculated based on the probability of the target variable being the first category. In the line 35 of "PredictorParsnip.R" 

`prediction = as.data.table(predict(self$model, newdata, type = "prob")[1])`

However, in the case of a binary classification problem, `stats::glm()` predicts the probability of the target variable being the second category.

For example:

``` r
# from fmeffects
pred_1 <- makePredictor(logistic_parsnip, Mroz87, "lfp")$predict(Mroz87)

pred_1 |> head(3)
#>    prediction
#>         <num>
#> 1:  0.2993375
#> 2:  0.2510059
#> 3:  0.2979661

# from other packages
Mroz87 |> 
  transmute(
    lfp, .pred = predict(logistic_parsnip$fit, type = "response")
  )  |> head(3)
#>   lfp     .pred
#> 1   1 0.7006625
#> 2   1 0.7489941
#> 3   1 0.7020339

pred_2 <- parsnip::predict_classprob.model_fit(logistic_parsnip, Mroz87)
pred_2 |> head(3)
#> # A tibble: 3 × 2
#>     `0`   `1`
#>   <dbl> <dbl>
#> 1 0.299 0.701
#> 2 0.251 0.749
#> 3 0.298 0.702
```

To ensure consistency with existing functions, I suggest considering a modification in the specification to calculate based on the probability of the target variable being the second category for binary classification problems. Alternatively, if feasible, allowing users to adjust the target category for prediction could be a beneficial addition.

Thank you for your attention to this matter. I appreciate your efforts in developing and maintaining this valuable package.

Sincerely,
Hiroto Tensho

**Comment by holgstr** [comment]
Dear Hiroto Tensho,
thank you so much for bringing this to our attention! We have implemented this immediately. Please find the updated package version on Github. The corresponding CRAN release should be available within a few days.
Best regards,
Holger

**Comment by Hirototensho** [comment]
Dear Holger Löwe,

I hope this message finds you well.

I wanted to express my sincere gratitude for promptly addressing the issue I raised. Your swift action in updating the package has been immensely helpful for my work.

Warm regards,

Hiroto Tensho
